<?xml version="1.0" encoding="UTF-8"?><testsuite errors="0" failures="6" name="functional.CalculatorTest" skipped="2" tests="15" time="0.02" timestamp="2017-08-233 05:40:30"><testcase classname="functional.CalculatorTest" name="Sub test1"><skipped/></testcase><testcase classname="functional.CalculatorTest" name="Sub test2"><failure message="expected:&lt;-23&gt; but was:&lt;-2&gt;" type="java.lang.AssertionError">expected:&lt;-23&gt; but was:&lt;-2&gt;</failure><system-err>expected:&lt;-23&gt; but was:&lt;-2&gt;
functional.CalculatorTest.subTest2(CalculatorTest.java:82)
</system-err></testcase><testcase classname="functional.CalculatorTest" name="Sub test4"/><testcase classname="functional.CalculatorTest" name="Sub test"><failure message="expected:&lt;2&gt; but was:&lt;-2&gt;" type="java.lang.AssertionError">expected:&lt;2&gt; but was:&lt;-2&gt;</failure><system-err>expected:&lt;2&gt; but was:&lt;-2&gt;
functional.CalculatorTest.subTest(CalculatorTest.java:31)
</system-err></testcase><testcase classname="functional.CalculatorTest" name="Division test"/><testcase classname="functional.CalculatorTest" name="Add test2"><failure message="expected:&lt;2&gt; but was:&lt;22&gt;" type="java.lang.AssertionError">expected:&lt;2&gt; but was:&lt;22&gt;</failure><system-err>expected:&lt;2&gt; but was:&lt;22&gt;
functional.CalculatorTest.addTest2(CalculatorTest.java:76)
</system-err></testcase><testcase classname="functional.CalculatorTest" name="Add test4"/><testcase classname="functional.CalculatorTest" name="Addition test 1"/><testcase classname="functional.CalculatorTest" name="Multiply test1"/><testcase classname="functional.CalculatorTest" name="Multiply test2"/><testcase classname="functional.CalculatorTest" name="Multiply test4"><failure message="expected:&lt;10&gt; but was:&lt;120&gt;" type="java.lang.AssertionError">expected:&lt;10&gt; but was:&lt;120&gt;</failure><system-err>expected:&lt;10&gt; but was:&lt;120&gt;
functional.CalculatorTest.multiplyTest4(CalculatorTest.java:112)
</system-err></testcase><testcase classname="functional.CalculatorTest" name="Division test1"/><testcase classname="functional.CalculatorTest" name="Division test2"><failure message="expected:&lt;10&gt; but was:&lt;1&gt;" type="java.lang.AssertionError">expected:&lt;10&gt; but was:&lt;1&gt;</failure><system-err>expected:&lt;10&gt; but was:&lt;1&gt;
functional.CalculatorTest.divisionTest2(CalculatorTest.java:94)
</system-err></testcase><testcase classname="functional.CalculatorTest" name="Division test4"><failure message="expected:&lt;10&gt; but was:&lt;1&gt;" type="java.lang.AssertionError">expected:&lt;10&gt; but was:&lt;1&gt;</failure><system-err>expected:&lt;10&gt; but was:&lt;1&gt;
functional.CalculatorTest.divisionTest4(CalculatorTest.java:118)
</system-err></testcase><testcase classname="functional.CalculatorTest" name="Multiply test"><skipped/></testcase></testsuite>